# 11월 16일(화) 공부

In [2]:
# numpy
import numpy as np

In [3]:
# numpy 배열 기본
v1 = np.array([1,2,3,4])
print(v1)

[1 2 3 4]


In [4]:
# 연속되거나 일정한 규칙을 가진 숫자
v1 = np.arange(5)
print(v1)

# 연속되거나 일정한 규칙을 가진 숫자, 데이터 형태 지정
v2 = np.arange(1,10,2, dtype=int)
print(v2)

v3 = np.arange(1,10,2, dtype=float)
print(v3)


[0 1 2 3 4]
[1 3 5 7 9]
[1. 3. 5. 7. 9.]


In [5]:
# 제곱값 생성
v4 = np.arange(1,10,2)**2
print(v4)

# 세제곱값 생성
v5 = np.arange(1,10,2)**3
print(v5)

[ 1  9 25 49 81]
[  1  27 125 343 729]


In [8]:
# 행렬만들기
v1 = np.arange(12)
print(v1)

v2 = v1.reshape(2,6)
print(v2)

v3 = v1.reshape(2,6, order='F') # 값을 열부터 채워 넣음 
print(v3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [9]:
# 행렬 계산

v1 = np.arange(1,5).reshape(2,2)

#덧셈
print("덧셈:", np.add(v1,v1))

#뺄셈
print("뺄셈:",np.subtract(v1,v1))

#곱셈
print("곱셈:",np.multiply(v1,v1))

#행렬연산
print("행렬연산:",np.dot(v1,v1))

덧셈: [[2 4]
 [6 8]]
뺄셈: [[0 0]
 [0 0]]
곱셈: [[ 1  4]
 [ 9 16]]
행렬연산: [[ 7 10]
 [15 22]]


In [10]:
# 다차원 행렬 만들기
v1 = np.arange(12)
print(v1)

v2=v1.reshape(2,3,2, order='F')
print(v2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


In [11]:
# 다차원 배열에서 요소의 최대값 및 최소값 반환
v3 = np.arange(3.5, 10.5, 2, dtype=float)
print(v3)

v4 = np.arange(1,5).reshape(2,2)
print(v4)

# 최대값
print("최대값 : ", np.amax(v3))

# 최소값
print("최소값 : ", np.amin(v4))


[3.5 5.5 7.5 9.5]
[[1 2]
 [3 4]]
최대값 :  9.5
최소값 :  1


In [12]:
# 다차원 배열의 데이터 타입 확인
v3 = np.arange(3.5, 10.5, 2, dtype=float)
print(v3)

v4 = np.arange(1,5).reshape(2,2)
print(v4)

print(v3.dtype)
print(v4.dtype)

[3.5 5.5 7.5 9.5]
[[1 2]
 [3 4]]
float64
int64


In [20]:
# 다차원 배열의 행, 열, 차원 확인
v3 = np.arange(3.5, 10.5, 2, dtype=float)
print(v3)

v4 = np.arange(0,12)
print(v4)

v5=v4.reshape(2,3,2)
print(v5)

print(v3.shape)
print(v5.shape)

[3.5 5.5 7.5 9.5]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
(4,)
(2, 3, 2)
