# 11월 29일 월 공부

In [37]:
import warnings
warnings.filterwarnings("ignore")

## K-NN 알고리즘 (2) 회귀

In [2]:
import pandas as pd

data = pd.read_csv('/Users/yerim/Desktop/빅데이터분석기사/BigData_data_최종본(1022)/house_price.csv' , encoding='utf-8')

X = data[data.columns[1:5]]
y = data[["house_value"]]

In [3]:
# train-test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42)

In [5]:
# MinMax정규화
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
X_scaled_train = scaler.transform(X_train)
X_scaled_test = scaler.transform(X_test)

In [9]:
# 기본 모델 적용 - KNeighborsRegressor
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor()
model.fit(X_scaled_train,y_train)

pred_train = model.predict(X_scaled_train)
pred_test = model.predict(X_scaled_test)

print("훈련 데이터 스코어 : " , model.score(X_scaled_train, y_train))
print("테스트 데이터 스코어 : " , model.score(X_scaled_test, y_test))

훈련 데이터 스코어 :  0.6804607237174459
테스트 데이터 스코어 :  0.5541889571372401


In [11]:
# 회귀모델 평가지표 - RMSE(Root Mean Squared Error)
import numpy as np
from sklearn.metrics import mean_squared_error
MSE_train = mean_squared_error(y_train, pred_train)
MSE_test = mean_squared_error(y_test, pred_test)

print("훈련데이터 RMSE : " , np.sqrt(MSE_train))
print("테스트데이터 RMSE : " , np.sqrt(MSE_test))

훈련데이터 RMSE :  53952.69804097723
테스트데이터 RMSE :  63831.91662964773


In [17]:
# 그리드 서치
from sklearn.model_selection import GridSearchCV
parameters = {'n_neighbors' : [1,3,5,7,9,11]}
grid_search = GridSearchCV(model, parameters, cv=5)
grid_search.fit(X_scaled_train, y_train)

print("Best params : ", grid_search.best_params_)
print("Best score : ", grid_search.best_score_)
print("Test score : ", grid_search.score(X_scaled_test, y_test))

Best params :  {'n_neighbors': 11}
Best score :  0.5638272489240468
Test score :  0.5879583242641135


In [18]:
# 랜덤서치
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

parameters = {'n_neighbors' : randint(low=1, high=20)}
random_search = RandomizedSearchCV(model, param_distributions = parameters, cv=5 , n_iter=20)
random_search.fit(X_scaled_train, y_train)

print("Best params : ", random_search.best_params_)
print("Best score : " , random_search.best_score_)
print("Test score : " , random_search.score(X_scaled_test, y_test))

Best params :  {'n_neighbors': 19}
Best score :  0.5776685542345874
Test score :  0.6004137013563815


## 3. 나이브베이즈 - (1) 분류

In [22]:
# 데이터 로드
import pandas as pd

data = pd.read_csv('/Users/yerim/Desktop/빅데이터분석기사/BigData_data_최종본(1022)/breast-cancer-wisconsin.csv' , encoding='utf-8')

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   code                         683 non-null    int64
 1   Clump_Thickness              683 non-null    int64
 2   Cell_Size                    683 non-null    int64
 3   Cell_Shape                   683 non-null    int64
 4   Marginal_Adhesion            683 non-null    int64
 5   Single_Epithelial_Cell_Size  683 non-null    int64
 6   Bare_Nuclei                  683 non-null    int64
 7   Bland_Chromatin              683 non-null    int64
 8   Normal_Nucleoli              683 non-null    int64
 9   Mitoses                      683 non-null    int64
 10  Class                        683 non-null    int64
dtypes: int64(11)
memory usage: 58.8 KB


In [24]:
# X 와 Y 나누기
X = data[data.columns[1:10]]
y = data[['Class']]

In [25]:
# train-test-split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,stratify=y,random_state=42)

In [28]:
# MinMaxScale
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
X_scaled_train = scaler.transform(X_train)
X_scaled_test = scaler.transform(X_test)

In [29]:
# 기본모델적용 나이브베이지 가우시안모델
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_scaled_train, y_train)
pred_train = model.predict(X_scaled_train)
pred_test = model.predict(X_scaled_test)

print("훈련데이터 성능 : " , model.score(X_scaled_train, y_train))
print("테스트데이터 성능 : " , model.score(X_scaled_test, y_test))

훈련데이터 성능 :  0.966796875
테스트데이터 성능 :  0.9590643274853801


/Users/yerim/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [31]:
# 기본모델 - 혼동행렬
from sklearn.metrics import confusion_matrix
conf_train = confusion_matrix(y_train, pred_train)
conf_test = confusion_matrix(y_test, pred_test)

print("훈련 데이터 오차행렬 : \n" , conf_train)
print("테스트 데이터 오차행렬 : \n" , conf_test)

훈련 데이터 오차행렬 : 
 [[319  14]
 [  3 176]]
테스트 데이터 오차행렬 : 
 [[106   5]
 [  2  58]]


In [33]:
# 기본 모델 - 상세 평가 지표
from sklearn.metrics import classification_report
crf_train = classification_report(y_train, pred_train)
crf_test = classification_report(y_test, pred_test)

print("훈련 데이터 상세 평가 지표 : \n", crf_train)
print("테스트 데이터 상세 평가 지표 : \n", crf_test)

훈련 데이터 상세 평가 지표 : 
               precision    recall  f1-score   support

           0       0.99      0.96      0.97       333
           1       0.93      0.98      0.95       179

    accuracy                           0.97       512
   macro avg       0.96      0.97      0.96       512
weighted avg       0.97      0.97      0.97       512

테스트 데이터 상세 평가 지표 : 
               precision    recall  f1-score   support

           0       0.98      0.95      0.97       111
           1       0.92      0.97      0.94        60

    accuracy                           0.96       171
   macro avg       0.95      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171



In [38]:
# 그리드 서치
from sklearn.model_selection import GridSearchCV
parameters = {'var_smoothing' : [0,1,2,3,4,5,6,7,8,9,10]}
grid_search = GridSearchCV(model, parameters, cv=5)
grid_search.fit(X_scaled_train, y_train)

print("Best params : " , grid_search.best_params_)
print("Best score : " , grid_search.best_score_)
print("Test score : " , grid_search.score(X_scaled_test, y_test))

Best params :  {'var_smoothing': 0}
Best score :  0.9648772130211307
Test score :  0.9590643274853801


In [40]:
# 랜덤서치
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

parameters = {'var_smoothing' : randint(low=0, high=20)}

random_search = RandomizedSearchCV(model, param_distributions=parameters , cv=5, n_iter=100)
random_search.fit(X_scaled_train, y_train)

print("Best params : " , random_search.best_params_)
print("Best score : " , random_search.best_score_)
print("Test score : " , random_search.score(X_scaled_test, y_test))

Best params :  {'var_smoothing': 0}
Best score :  0.9648772130211307
Test score :  0.9590643274853801


## 3. 나이브베이즈 - (2) 회귀

In [41]:
# 데이터로드
import pandas as pd

data = pd.read_csv('/Users/yerim/Desktop/빅데이터분석기사/BigData_data_최종본(1022)/house_price.csv', encoding='utf-8')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17689 entries, 0 to 17688
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   housing_age  17689 non-null  int64  
 1   income       17689 non-null  float64
 2   bedrooms     17689 non-null  float64
 3   households   17689 non-null  float64
 4   rooms        17689 non-null  float64
 5   house_value  17689 non-null  int64  
dtypes: float64(4), int64(2)
memory usage: 829.3 KB


In [42]:
# X 와 Y  나누기
X = data[data.columns[0:5]]
y = data[['house_value']]

In [43]:
# train-test-split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42)

In [48]:
# MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
X_scaled_train = scaler.transform(X_train)
X_scaled_test = scaler.transform(X_test)

In [49]:
# 기본 모델 적용 - 나이브베이즈 회귀모델 알고리즘은 BayesianRidge
from sklearn.linear_model import BayesianRidge
model = BayesianRidge()
model.fit(X_scaled_train, y_train)

pred_train = model.predict(X_scaled_train)
pred_test = model.predict(X_scaled_test)

print("훈련데이터 모델 성능 : " , model.score(X_scaled_train, y_train))
print("테스트데이터 모델 성능 : ", model.score(X_scaled_test, y_test))

훈련데이터 모델 성능 :  0.5706920449333218
테스트데이터 모델 성능 :  0.5826111218474419


In [51]:
# 오차 확인 - RMSE
from sklearn.metrics import mean_squared_error
import numpy as np

MSE_train = mean_squared_error(y_train, pred_train)
MSE_test = mean_squared_error(y_test, pred_test)
print("훈련 데이터 RMSE오차확인 : {:.4f}".format(np.sqrt(MSE_train)))
print("테스트 데이터 RMSE오차확인 : {:.4f}".format(np.sqrt(MSE_test)))

훈련 데이터 RMSE오차확인 : 62536.7794
테스트 데이터 RMSE오차확인 : 61763.6439


In [53]:
# 그리드서치
from sklearn.model_selection import GridSearchCV
parameters = {'alpha_1' : [1e-06, 1e-05, 1e-04, 1e-03, 1e-02, 1e-01, 1, 2, 3, 4] , 
              'lambda_1': [1e-06, 1e-05, 1e-04, 1e-03, 1e-02, 1e-01, 1, 2, 3, 4]}
grid_search = GridSearchCV(model, parameters, cv=5)
grid_search.fit(X_scaled_train, y_train)

print("Best Params : " , grid_search.best_params_)
print("Best Score : " , grid_search.best_score_)
print("Test Score : " , grid_search.score(X_scaled_test, y_test))

Best Params :  {'alpha_1': 4, 'lambda_1': 1e-06}
Best Score :  0.5702758458286125
Test Score :  0.5826111202240445


In [56]:
# 랜덤서치
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

parameters = {'alpha_1' : randint(low=1e-06, high =10) , 
             'lambda_1' : randint(low=1e-06, high=10)}

random_search = RandomizedSearchCV(model, param_distributions = parameters, cv=5, n_iter=100)
random_search.fit(X_scaled_train, y_train)

print("Best params : ", random_search.best_params_)
print("Best score : ", random_search.best_score_)
print("Test score : " , random_search.score(X_scaled_test, y_test))

Best params :  {'alpha_1': 9, 'lambda_1': 0}
Best score :  0.5702758458751305
Test score :  0.5826111181963927


## 4. 인공신경망 - (1) 분류

In [57]:
# 데이터 로드
import pandas as pd
data = pd.read_csv('/Users/yerim/Desktop/빅데이터분석기사/BigData_data_최종본(1022)/breast-cancer-wisconsin.csv', encoding='utf-8')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   code                         683 non-null    int64
 1   Clump_Thickness              683 non-null    int64
 2   Cell_Size                    683 non-null    int64
 3   Cell_Shape                   683 non-null    int64
 4   Marginal_Adhesion            683 non-null    int64
 5   Single_Epithelial_Cell_Size  683 non-null    int64
 6   Bare_Nuclei                  683 non-null    int64
 7   Bland_Chromatin              683 non-null    int64
 8   Normal_Nucleoli              683 non-null    int64
 9   Mitoses                      683 non-null    int64
 10  Class                        683 non-null    int64
dtypes: int64(11)
memory usage: 58.8 KB


In [59]:
# X 와 Y 나누기
X = data.iloc[:,1:10]
y = data[['Class']]

In [61]:
# train-test-split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,stratify=y,random_state=42)

In [62]:
# MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
X_scaled_train = scaler.transform(X_train)
X_scaled_test = scaler.transform(X_test)

In [65]:
# 기본 모델 적용하기 - MLPClassifier
from sklearn.neural_network import MLPClassifier
model = MLPClassifier()
model.fit(X_scaled_train, y_train)

pred_train = model.predict(X_scaled_train)
pred_test = model.predict(X_scaled_test)

print("훈련 데이터 성능 : " , model.score(X_scaled_train, y_train))
print("테스트 데이터 성능 : " , model.score(X_scaled_test, y_test))

훈련 데이터 성능 :  0.974609375
테스트 데이터 성능 :  0.9590643274853801


In [66]:
# 오차행렬 (혼돈행렬) 
from sklearn.metrics import confusion_matrix

conf_train = confusion_matrix(y_train, pred_train)
conf_test = confusion_matrix(y_test, pred_test)

print("훈련데이터 오차행렬 : \n" , conf_train)
print("테스트데이터 오차행렬 : \n" , conf_test)

훈련데이터 오차행렬 : 
 [[328   5]
 [  8 171]]
테스트데이터 오차행렬 : 
 [[106   5]
 [  2  58]]


In [70]:
# 상세지표
from sklearn.metrics import classification_report

crf_train = classification_report(y_train, pred_train)
crf_test = classification_report(y_test, pred_test)

print("훈련데이터 상세 지표 : \n" , crf_train)
print("테스트데이터 상세 지표 : \n" , crf_test)

훈련데이터 상세 지표 : 
               precision    recall  f1-score   support

           0       0.98      0.98      0.98       333
           1       0.97      0.96      0.96       179

    accuracy                           0.97       512
   macro avg       0.97      0.97      0.97       512
weighted avg       0.97      0.97      0.97       512

테스트데이터 상세 지표 : 
               precision    recall  f1-score   support

           0       0.98      0.95      0.97       111
           1       0.92      0.97      0.94        60

    accuracy                           0.96       171
   macro avg       0.95      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171



In [87]:
# 그리드 서치
from sklearn.model_selection import GridSearchCV
parameters = {'hidden_layer_sizes' : [10, 30, 50, 100] , 'solver' : ['sdg','adam'], 'activation' : ['tanh','relu']}
grid_search = GridSearchCV(MLPClassifier(), parameters, cv=5)
grid_search.fit(X_scaled_train, y_train)

print("Best params : " , grid_search.best_params_)
print("Best score : " , grid_search.best_score_)
print("Test score : " , grid_search.score(X_scaled_test, y_test))

Best params :  {'activation': 'tanh', 'hidden_layer_sizes': 50, 'solver': 'adam'}
Best score :  0.9765086617171141
Test score :  0.9590643274853801


In [88]:
# 랜덤 서치
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint
parameters = {'hidden_layer_sizes' : randint(low=10, high=100), 'solver':['sgd','adam'], 'activation' : ['tanh','relu']}
random_search = RandomizedSearchCV(model, param_distributions = parameters , cv=5, n_iter=10)
random_search.fit(X_scaled_train, y_train)

print("Best params : ", random_search.best_params_)
print("Best score : " , random_search.best_score_)
print("Test score : " , random_search.score(X_scaled_test, y_test))

Best params :  {'activation': 'relu', 'hidden_layer_sizes': 11, 'solver': 'adam'}
Best score :  0.976546735198934
Test score :  0.9590643274853801


## 4. 인공 신경망 - (2) 회귀

In [89]:
# 데이터 로드
import pandas as pd
data = pd.read_csv('/Users/yerim/Desktop/빅데이터분석기사/BigData_data_최종본(1022)/house_price.csv' , encoding='utf-8')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17689 entries, 0 to 17688
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   housing_age  17689 non-null  int64  
 1   income       17689 non-null  float64
 2   bedrooms     17689 non-null  float64
 3   households   17689 non-null  float64
 4   rooms        17689 non-null  float64
 5   house_value  17689 non-null  int64  
dtypes: float64(4), int64(2)
memory usage: 829.3 KB


In [90]:
# X와 Y나누기
X = data.iloc[:,1:5]
y = data[['house_value']]

In [91]:
# train-test-split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [93]:
# MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
X_scaled_train = scaler.transform(X_train)
X_scaled_test = scaler.transform(X_test)

In [94]:
# 기본 모델 적용
from sklearn.neural_network import MLPRegressor
model = MLPRegressor()
model.fit(X_scaled_train, y_train)
pred_train = model.predict(X_scaled_train)
pred_test = model.predict(X_scaled_test)

print("훈련 데이터 성능 : " , model.score(X_scaled_train, y_train))
print("테스트 데이터 성능 : " , model.score(X_scaled_test, y_test))

훈련 데이터 성능 :  -2.7305811667662403
테스트 데이터 성능 :  -2.688568703466019


In [96]:
# 오차 확인 - RMSE
import numpy as np
from sklearn.metrics import mean_squared_error
MSE_train = mean_squared_error(y_train, pred_train)
MSE_test = mean_squared_error(y_test, pred_test)

print("훈련 데이터 RMSE : " , np.sqrt(MSE_train))
print("테스트 데이터 RMSE : " , np.sqrt(MSE_test))

훈련 데이터 RMSE :  184348.36520649013
테스트 데이터 RMSE :  183607.92071800423


In [97]:
# 튜닝 모델 
## 그리드서치 , 랜덤서치는 "MLPRegressor" 모델에 적합하지 않다. -> 파라미터가 너무 많아서 복잡함.
# hidden layer 를 깊게 셜정해주면 좋음.
# hidden_layer_sizes 쌓는법 : 튜플로 ( n, n , n) -> (64,64,64) : 한 층에 64개 노드씩 3개 층
from sklearn.neural_network import MLPRegressor
model = MLPRegressor(hidden_layer_sizes=(64,64,64),activation='relu',random_state=1,max_iter=2000)
model.fit(X_scaled_train, y_train)
pred_train = model.predict(X_scaled_train)
pred_test = model.predict(X_scaled_test)

print("훈련 데이터 점수 : " , model.score(X_scaled_train, y_train))
print("테스트 데이터 점수 : ", model.score(X_scaled_test, y_test))

훈련 데이터 점수 :  0.566197903746314
테스트 데이터 점수 :  0.5840866843135079


In [98]:
# RMSE
import numpy as np
from sklearn.metrics import mean_squared_error

MSE_train = mean_squared_error(y_train, pred_train)
MSE_test = mean_squared_error(y_test, pred_test)

print("훈련 데이터 MSE : " , np.sqrt(MSE_train))
print("테스트 데이터 MSE : " , np.sqrt(MSE_test))

훈련 데이터 MSE :  62863.255358058195
테스트 데이터 MSE :  61654.37310884089


## 5. 서포트벡터머신 - (1)분류

In [99]:
# 데이터임포트
import pandas as pd
data_1 = pd.read_csv('/Users/yerim/Desktop/빅데이터분석기사/BigData_data_최종본(1022)/breast-cancer-wisconsin.csv', encoding='utf-8')
data_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   code                         683 non-null    int64
 1   Clump_Thickness              683 non-null    int64
 2   Cell_Size                    683 non-null    int64
 3   Cell_Shape                   683 non-null    int64
 4   Marginal_Adhesion            683 non-null    int64
 5   Single_Epithelial_Cell_Size  683 non-null    int64
 6   Bare_Nuclei                  683 non-null    int64
 7   Bland_Chromatin              683 non-null    int64
 8   Normal_Nucleoli              683 non-null    int64
 9   Mitoses                      683 non-null    int64
 10  Class                        683 non-null    int64
dtypes: int64(11)
memory usage: 58.8 KB


In [101]:
# X 와 Y 분류
X1 = data_1.iloc[:,1:10]
y1 = data_1[['Class']]

In [102]:
# train-test-split
from sklearn.model_selection import train_test_split
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, stratify=y1, random_state=42)

In [103]:
# MinMaxScale
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X1_train)
X1_scaled_train = scaler.transform(X1_train)
X1_scaled_test = scaler.transform(X1_test)

In [105]:
# 기본 모델 적용 - SVC
from sklearn.svm import SVC
model = SVC()
model.fit(X1_scaled_train, y1_train)

pred_train = model.predict(X1_scaled_train)
pred_test = model.predict(X1_scaled_test)

print("훈련 데이터 점수 : " , model.score(X1_scaled_train, y1_train))
print("테스트 데이터 점수 : " , model.score(X1_scaled_test, y1_test))

훈련 데이터 점수 :  0.984375
테스트 데이터 점수 :  0.9649122807017544


In [107]:
# 혼돈행렬
from sklearn.metrics import confusion_matrix
conf_train = confusion_matrix(y1_train, pred_train)
conf_test = confusion_matrix(y1_test, pred_test)

print("훈련 데이터 혼돈 행렬 : \n" , conf_train)
print("테스트 데이터 혼돈 행렬 : \n" , conf_test)

훈련 데이터 혼돈 행렬 : 
 [[329   4]
 [  4 175]]
테스트 데이터 혼돈 행렬 : 
 [[106   5]
 [  1  59]]


In [108]:
# 상세지표
from sklearn.metrics import classification_report
cfr_train = classification_report(y1_train, pred_train)
cfr_test = classification_report(y1_test, pred_test)

print("훈련 데이터 상세 지표 : \n" , cfr_train )
print("테스트 데이터 상세 지표 : \n" , cfr_test)

훈련 데이터 상세 지표 : 
               precision    recall  f1-score   support

           0       0.99      0.99      0.99       333
           1       0.98      0.98      0.98       179

    accuracy                           0.98       512
   macro avg       0.98      0.98      0.98       512
weighted avg       0.98      0.98      0.98       512

테스트 데이터 상세 지표 : 
               precision    recall  f1-score   support

           0       0.99      0.95      0.97       111
           1       0.92      0.98      0.95        60

    accuracy                           0.96       171
   macro avg       0.96      0.97      0.96       171
weighted avg       0.97      0.96      0.97       171



In [112]:
# 그리드 서치
from sklearn.model_selection import GridSearchCV
parameters = {'kernel':['rbf','linear'] , 
             'C':[0.001, 0.01, 0.1, 1.0 , 10, 100],
             'gamma' : [0.001, 0.01, 0.1, 1.0 , 10, 100]}
grid_search = GridSearchCV(SVC(), parameters, cv=5)
grid_search.fit(X1_scaled_train, y1_train)

print("Best params : ", grid_search.best_params_)
print("Best score : " , grid_search.best_score_)
print("Test score : ", grid_search.score(X1_scaled_test, y1_test))

Best params :  {'C': 1.0, 'gamma': 0.001, 'kernel': 'linear'}
Best score :  0.9745669141442985
Test score :  0.9590643274853801


In [113]:
# 랜덤 서치
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint
parameters = {'kernel' : ['rbf', 'linear'],
             'C' : randint(low=0.001 , high=100),
             'gamma' : randint(low=0.001, high=100)}
random_search = RandomizedSearchCV(SVC(), param_distributions = parameters , cv=5, n_iter=100)
random_search.fit(X1_scaled_train, y1_train)

print("Best params : " ,random_search.best_params_)
print("Best score : " , random_search.best_score_)
print("Test score : " , random_search.score(X1_scaled_test, y1_test))

Best params :  {'C': 5, 'gamma': 45, 'kernel': 'linear'}
Best score :  0.9765086617171141
Test score :  0.9590643274853801


## 5. 서포트벡터머신 - (2)회귀 

In [114]:
# 데이터 로드
import pandas as pd
data2 = pd.read_csv('/Users/yerim/Desktop/빅데이터분석기사/BigData_data_최종본(1022)/house_price.csv', encoding='utf-8')
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17689 entries, 0 to 17688
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   housing_age  17689 non-null  int64  
 1   income       17689 non-null  float64
 2   bedrooms     17689 non-null  float64
 3   households   17689 non-null  float64
 4   rooms        17689 non-null  float64
 5   house_value  17689 non-null  int64  
dtypes: float64(4), int64(2)
memory usage: 829.3 KB


In [115]:
# X 와 Y 나누기
X2 = data.iloc[:,1:5]
y2 = data[['house_value']]

In [116]:
# train_test_split
from sklearn.model_selection import train_test_split
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, random_state=42)

In [117]:
# MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X2_train)

X2_scaled_train = scaler.transform(X2_train)
X2_scaled_test = scaler.transform(X2_test)

In [124]:
# 기본 모델 - SVR
from sklearn.svm import SVR
model = SVR(kernel='poly')
model.fit(X2_scaled_train, y2_train)

pred_train = model.predict(X2_scaled_train)
pred_test = model.predict(X2_scaled_test)

print("훈련 데이터 스코어 : " , model.score(X2_scaled_train , y2_train))
print("테스트 데이터 스코어 : " , model.score(X2_scaled_test, y2_test))

훈련 데이터 스코어 :  0.45177025652823866
테스트 데이터 스코어 :  0.46997708096191404


In [125]:
# RMSE 
import numpy as np
from sklearn.metrics import mean_squared_error

MSE_train = mean_squared_error(y2_train, pred_train)
MSE_test = mean_squared_error(y2_test, pred_test)

print("훈련데이터 RMSE : ", np.sqrt(MSE_train))
print("테스트데이터 RMSe : ", np.sqrt(MSE_test))

훈련데이터 RMSE :  70669.55244251259
테스트데이터 RMSe :  69600.08959938576


In [128]:
# 그리드서치
from sklearn.model_selection import GridSearchCV
parameters = {'kernel':['poly'],
             'C' : [0.01, 0.1, 1, 10],
             'gamma' : [0.01, 0.1, 1, 10]}
grid_search = GridSearchCV(model , parameters , cv=5)
grid_search.fit(X2_scaled_train, y2_train)

print("Best params : " , grid_search.best_params_)
print("Best score : " , grid_search.best_score_)
print("Test score : " , grid_search.score(X2_scaled_test, y2_test))

Best params :  {'C': 10, 'gamma': 10, 'kernel': 'poly'}
Best score :  0.48878076027112094
Test score :  0.5092229851181337


In [129]:
# 랜덤서치
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

parameters = {'kernel' : ['poly'],
             'C' : randint(low=0.01, high=10),
             'gamma' : randint(low=0.01, high=10)}

random_search = RandomizedSearchCV(model,param_distributions = parameters, cv=5, n_iter=20)
random_search.fit(X2_scaled_train, y2_train)

print("Best params : " , random_search.best_params_)
print("Best score : ", random_search.best_score_)
print("Test score : ", random_search.score(X2_scaled_test, y2_test))

Best params :  {'C': 9, 'gamma': 8, 'kernel': 'poly'}
Best score :  0.46459467651190567
Test score :  0.4890335953909718


## 6. 의사결정나무 - (1) 분류

In [130]:
# 모델 사용 - DecisionTreeClassifier

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X1_scaled_train, y1_train)

pred_train = model.predict(X1_scaled_train)
pred_test = model.predict(X1_scaled_test)

print("훈련 데이터 점수 : " , model.score(X1_scaled_train , y1_train))
print("테스트 데이터 점수 : " , model.score(X1_scaled_test, y1_test))

훈련 데이터 점수 :  1.0
테스트 데이터 점수 :  0.9532163742690059


In [131]:
# 혼돈행렬
from sklearn.metrics import confusion_matrix
conf_train = confusion_matrix(y1_train , pred_train)
conf_test = confusion_matrix(y1_test, pred_test)

print("훈련데이터 혼돈행렬 : \n" , conf_train)
print("테스트데이터 혼동행렬 : \n" , conf_test)

훈련데이터 혼돈행렬 : 
 [[333   0]
 [  0 179]]
테스트데이터 혼동행렬 : 
 [[106   5]
 [  3  57]]


In [132]:
# 상세 평가 지수
from sklearn.metrics import classification_report

cfr_train = classification_report(y1_train, pred_train)
cfr_test = classification_report(y1_test, pred_test)

print("훈련데이테 상세평가지수 : \n" , cfr_train)
print("테스트데이터 상세평가지수 : \n" , cfr_test)

훈련데이테 상세평가지수 : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       333
           1       1.00      1.00      1.00       179

    accuracy                           1.00       512
   macro avg       1.00      1.00      1.00       512
weighted avg       1.00      1.00      1.00       512

테스트데이터 상세평가지수 : 
               precision    recall  f1-score   support

           0       0.97      0.95      0.96       111
           1       0.92      0.95      0.93        60

    accuracy                           0.95       171
   macro avg       0.95      0.95      0.95       171
weighted avg       0.95      0.95      0.95       171



In [134]:
# 그리드서치
from sklearn.model_selection import GridSearchCV
parameters = {'max_depth' : range(2,20,2), 
             'min_samples_leaf' : range(1,50,2)}
grid_search = GridSearchCV(model, parameters, cv=5)
grid_search.fit(X1_scaled_train, y1_train)

print("Best Param : " , grid_search.best_params_)
print("Best score : ", grid_search.best_score_)
print("Test score : ", grid_search.score(X1_scaled_test, y1_test))

Best Param :  {'max_depth': 14, 'min_samples_leaf': 1}
Best score :  0.9667237768893966
Test score :  0.9532163742690059


In [136]:
# 랜덤서치
from sklearn.model_selection import RandomizedSearchCV 
from scipy.stats import randint

parameters = {'max_depth' : randint(low=1, high=20),
             'min_samples_leaf' : randint(low=1, high=50)}

random_search = RandomizedSearchCV(model, param_distributions = parameters, cv=5, n_iter=20)
random_search.fit(X1_scaled_train, y1_train)

print("Best param : ", random_search.best_params_)
print("Best score : ", random_search.best_score_)
print("Test score : ", random_search.score(X1_scaled_test, y1_test))

Best param :  {'max_depth': 2, 'min_samples_leaf': 8}
Best score :  0.9472872644203314
Test score :  0.935672514619883


## 6. 의사결정나무 - (2) 회귀

In [138]:
# 기본 모델 적용 - DecisionTreeRegressor
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor()
model.fit(X2_scaled_train, y2_train)

pred_train = model.predict(X2_scaled_train)
pred_test = model.predict(X2_scaled_test)

print("훈련 데이터 점수 : " , model.score(X2_scaled_train, y2_train))
print("테스트 데이터 점수 : " , model.score(X2_scaled_test, y2_test))

훈련 데이터 점수 :  1.0
테스트 데이터 점수 :  0.21820975548485466


In [139]:
# RMSE
from sklearn.metrics import mean_squared_error
import numpy as np

MSE_train = mean_squared_error(y2_train, pred_train)
MSE_test = mean_squared_error(y2_test, pred_test)

print("훈련 데이터 RMSE" , np.sqrt(MSE_train))
print("테스트 데이터 RMSE" , np.sqrt(MSE_test))

훈련 데이터 RMSE 0.0
테스트 데이터 RMSE 84529.36321500909


In [140]:
# 그리드 서치
from sklearn.model_selection import GridSearchCV
parameters = {'max_depth' : range(1,20,2), 
             'min_samples_leaf' : range(1,50,2)}

grid_search = GridSearchCV(model, parameters , cv=5)
grid_search.fit(X2_scaled_train, y2_train)

print("Bsst param : " , grid_search.best_params_)
print("Best score : " , grid_search.best_score_)
print("Test score : " , grid_search.score(X2_scaled_test, y2_test))

Bsst param :  {'max_depth': 9, 'min_samples_leaf': 49}
Best score :  0.558919575352857
Test score :  0.5772120054189142


In [143]:
# 랜덤 서치
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint
parameters = {'max_depth' : randint(1,20,2) , 
             'min_samples_leaf' : randint(1,50,2)}

random_search = RandomizedSearchCV(model, param_distributions = parameters , cv=5, n_iter=20)
random_search.fit(X2_scaled_train, y2_train)

print("Best params : ", random_search.best_params_)
print("Best score : " , random_search.best_score_)
print("Test score : " , random_search.score(X2_scaled_test, y2_test))

Best params :  {'max_depth': 10, 'min_samples_leaf': 46}
Best score :  0.5579972830847009
Test score :  0.5762173631108735
